/** Curated icons for menu categories. Format: pack:IconName */
export const CATEGORY_ICONS = [
  "lu:LuCoffee",
  "lu:LuCupSoda",
  "lu:LuGlassWater",
  "lu:LuWine",
  "lu:LuBeer",
  "lu:LuMartini",
  "lu:LuCroissant",
  "lu:LuEgg",
  "lu:LuSandwich",
  "lu:LuPizza",
  "lu:LuSoup",
  "lu:LuSalad",
  "lu:LuUtensilsCrossed",
  "lu:LuChefHat",
  "lu:LuBeef",
  "lu:LuDrumstick",
  "lu:LuFish",
  "lu:LuCake",
  "lu:LuCakeSlice",
  "lu:LuIceCreamCone",
  "lu:LuCookie",
  "lu:LuCandy",
  "lu:LuApple",
  "lu:LuCherry",
  "lu:LuCarrot",
  "lu:LuLeaf",
  "lu:LuPopcorn",
  "lu:LuFlame",
  "lu:LuStar",
  "lu:LuClock",
] as const;
